spring:
  application:
    name: manager-application
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: password
  jpa:
    open-in-view: true
server:
  port: 8080

catalogue:
  service:
    url: http://localhost:8081
    username: catalogue_user
    password: password